main_app:
  title: "Arduino Serial App"
  width: 800
  height: 600

ui:
  font_family: "Times New Roman"
  font_size: 14
  font_color: "#000000" 

  buttons:
    send:
      text_color: "#FFFFFF"
      bg_color: "#31CAE8"
    disconnect:
      text_color: "#FFFFFF"
      bg_color: "#FF4136"
    close:
      text_color: "#FFFFFF"
      bg_color: "#111111"

  textboxes:
    input:
      text_color: "#000000"
      bg_color: "#FFFFFF"
    output:
      text_color: "#000000"
      bg_color: "#FFFFFF"
